# Generated by Django 5.1.7 on 2026-07-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='filmbazuser',
            name='account_fil_created_a1de03_idx',
        ),
    ]
