# Generated by Django 5.1.7 on 2026-07-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('film', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmbazuser',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, related_name='fans', to='film.genre'),
        ),
        migrations.AddField(
            model_name='filmbazuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='filmbazuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='filmbazuser',
            index=models.Index(fields=['username'], name='account_fil_usernam_61c36c_idx'),
        ),
    ]
