# Generated by Django 5.1 on 2024-08-18 08:37

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmbazuser',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default=1, force_format=None, keep_meta=True, quality=100, scale=None, size=[500, 500], upload_to='profile_images/'),
            preserve_default=False,
        ),
    ]
