# Generated by Django 5.1 on 2024-08-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_filmbazuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Criticism', 'criticism'), ('Proposal', 'proposal'), ('Report', ' report')])),
                ('text', models.TextField(max_length=2000)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
