# Generated by Django 5.1 on 2024-08-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(choices=[('Criticism', 'انتقاد'), ('Proposal', 'پیشنهاد'), ('Report', ' گزارش')]),
        ),
    ]
