# Generated by Django 5.1 on 2024-08-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_ticket_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(choices=[('Criticism', 'انتقاد'), ('Proposal', 'پیشنهاد'), ('Report', ' گزارش')], max_length=9),
        ),
    ]
