# Generated by Django 5.1.7 on 2026-07-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('save', 'Save'), ('comment', 'Comment'), ('share', 'Share'), ('search', 'Search'), ('watch', 'Watch')], max_length=10)),
                ('weight', models.FloatField(help_text='وزن عددی هر نوع تعامل برای مدل CF')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
