# Generated by Django 5.1.7 on 2026-07-12 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0003_remove_comment_film_commen_created_28b20c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('save', 'Save'), ('comment', 'Comment'), ('share', 'Share'), ('search', 'Search')], max_length=10)),
                ('weight', models.FloatField(help_text='وزن عددی هر نوع تعامل برای مدل CF')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='film.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'movie'], name='analytics_i_user_id_e06022_idx'), models.Index(fields=['interaction_type'], name='analytics_i_interac_96c20d_idx')],
            },
        ),
    ]
