# Generated by Django 5.1.7 on 2026-06-08 11:55

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_name', models.CharField(max_length=200)),
                ('en_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=50, scale=None, size=[200, 200], upload_to='people/crews/')),
            ],
            options={
                'ordering': ['en_name'],
            },
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_name', models.CharField(max_length=200)),
                ('en_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=50, scale=None, size=[200, 200], upload_to='people/casts/')),
                ('movies', models.ManyToManyField(blank=True, related_name='casts', to='film.movie')),
            ],
            options={
                'ordering': ['en_name'],
            },
        ),
        migrations.CreateModel(
            name='MovieCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('director', 'Director'), ('producer', 'Producer'), ('writer', 'Writer')], max_length=20)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_crews', to='people.crewmember')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_crews', to='film.movie')),
            ],
            options={
                'unique_together': {('movie', 'crew', 'role')},
            },
        ),
    ]
