# Generated by Django 5.1.7 on 2026-06-04 13:09

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_name', models.CharField(max_length=200)),
                ('en_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=50, scale=None, size=[200, 200], upload_to='people/casts/')),
                ('movies', models.ManyToManyField(related_name='casts', to='film.movie')),
            ],
            options={
                'ordering': ['en_name'],
                'indexes': [models.Index(fields=['en_name'], name='people_cast_en_name_7658f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_name', models.CharField(max_length=200)),
                ('en_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('director', 'Director'), ('producer', 'Producer'), ('writer', 'Writer'), ('cinematographer', 'Cinematographer'), ('editor', 'Editor'), ('composer', 'Composer')], max_length=50)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=50, scale=None, size=[200, 200], upload_to='people/crews/')),
                ('movies', models.ManyToManyField(related_name='crews', to='film.movie')),
            ],
            options={
                'ordering': ['en_name'],
                'indexes': [models.Index(fields=['en_name'], name='people_crew_en_name_02e751_idx')],
            },
        ),
    ]
