#!/bin/bash
set -e

psql \
    -v ON_ERROR_STOP=1 \
    --username "$POSTGRES_USER" \
    --dbname "$POSTGRES_DB" <<EOF

DO
$$
BEGIN
    IF NOT EXISTS (
        SELECT
        FROM pg_roles
        WHERE rolname = '${ML_DB_USER}'
    ) THEN

        CREATE ROLE ${ML_DB_USER}
        LOGIN
        PASSWORD '${ML_DB_PASSWORD}';

    ELSE

        ALTER ROLE ${ML_DB_USER}
        WITH PASSWORD '${ML_DB_PASSWORD}';

    END IF;
END
$$;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${ML_DB_USER};

GRANT USAGE ON SCHEMA public TO ${ML_DB_USER};

GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${ML_DB_USER};

GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO ${ML_DB_USER};

ALTER DEFAULT PRIVILEGES
FOR ROLE ${POSTGRES_USER}
IN SCHEMA public
GRANT SELECT ON TABLES TO ${ML_DB_USER};

ALTER DEFAULT PRIVILEGES
FOR ROLE ${POSTGRES_USER}
IN SCHEMA public
GRANT SELECT ON SEQUENCES TO ${ML_DB_USER};

EOF