# Generated by Django 5.1.7 on 2026-05-31 12:05

import django.db.models.deletion
import django_resized.forms
import film.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_name', models.CharField(max_length=200)),
                ('en_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['en_name'],
                'indexes': [models.Index(fields=['en_name'], name='film_catego_en_name_5914c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_name', models.CharField(max_length=200)),
                ('en_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['en_name'],
                'indexes': [models.Index(fields=['en_name'], name='film_genre_en_name_0fc05b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[300, 400], upload_to=film.models.image_sorter)),
                ('backdrop', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[1600, 900], upload_to=film.models.image_sorter)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=255, null=True)),
                ('images_downloaded', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('english_title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('tmdb_rate', models.FloatField(default=0)),
                ('year', models.DateField(blank=True, max_length=4, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('runtime', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tmdb_id', models.PositiveIntegerField(unique=True)),
                ('is_dubbed', models.BooleanField(default=False)),
                ('is_serie', models.BooleanField(default=False)),
                ('adults', models.BooleanField(default=False)),
                ('details_fetched', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('last_tmdb_sync', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='movies', to='film.category')),
                ('genres', models.ManyToManyField(related_name='movies', to='film.genre')),
                ('users_saved', models.ManyToManyField(blank=True, related_name='saves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='film.movie')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-created'], name='film_movie_created_0c27ef_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created'], name='film_commen_created_28b20c_idx'),
        ),
    ]
