# Generated by Django 5.1.7 on 2026-04-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='episode_number',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='season',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_serie',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
