# Generated by Django 5.1.7 on 2026-07-22 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='crew_members',
            field=models.ManyToManyField(blank=True, related_name='movies', through='people.MovieCrew', to='people.crewmember'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='film.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='users_liked',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='users_saved',
            field=models.ManyToManyField(blank=True, related_name='saves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='film.movie'),
        ),
        migrations.AddField(
            model_name='movieepisode',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='film.movie'),
        ),
        migrations.AddField(
            model_name='movieepisode',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='seened_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movietrailer',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trailer', to='film.movie'),
        ),
        migrations.AddField(
            model_name='movietrailer',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='seened_trailers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watchtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_times', to='film.movieepisode'),
        ),
        migrations.AddField(
            model_name='watchtime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_times', to=settings.AUTH_USER_MODEL),
        ),
    ]
