# Generated by Django 5.1.7 on 2026-07-21 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefile',
            name='hour',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moviefile',
            name='minute',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moviefile',
            name='second',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='watchtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_times', to='film.moviefile'),
        ),
    ]
