# Generated by Django 5.1 on 2024-08-09 12:32

import django_resized.forms
import film.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_alter_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[300, 400], upload_to=film.models.image_sorter),
        ),
    ]
