# Generated by Django 5.1.7 on 2026-07-12 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='film_commen_created_28b20c_idx',
        ),
        migrations.RemoveIndex(
            model_name='genre',
            name='film_genre_en_name_0fc05b_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='film_movie_created_0c27ef_idx',
        ),
        migrations.AddField(
            model_name='movie',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, related_name='fans', to='film.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='users_liked',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
