# Generated by Django 5.1.7 on 2026-07-21 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_moviefile_hour_moviefile_minute_moviefile_second_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.PositiveSmallIntegerField(default=1)),
                ('season', models.PositiveSmallIntegerField(default=1)),
                ('file', models.FileField(upload_to='movies/movies/')),
                ('hour', models.PositiveSmallIntegerField(default=0)),
                ('minute', models.PositiveSmallIntegerField(default=0)),
                ('second', models.PositiveSmallIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='film.movie')),
                ('seen_by', models.ManyToManyField(blank=True, related_name='seened_movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='watchtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_times', to='film.movieepisode'),
        ),
        migrations.DeleteModel(
            name='MovieFile',
        ),
    ]
