# Generated by Django 5.1 on 2024-08-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_alter_movie_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='film_movie_year_4f47a0_idx',
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
