# Generated by Django 5.1 on 2024-08-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='english_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
