# Generated by Django 5.1 on 2024-08-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_movie_english_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='composer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='editor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='producer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
