# Generated by Django 5.1 on 2024-08-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_alter_movie_composer_alter_movie_editor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='movie_count',
        ),
        migrations.AddField(
            model_name='cast',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
