# Generated by Django 5.1 on 2024-08-12 15:01

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=50, scale=None, size=[200, 200], upload_to='casts'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
