# Generated by Django 5.1 on 2024-08-23 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0012_alter_cast_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='users_saved',
            field=models.ManyToManyField(related_name='saves', to=settings.AUTH_USER_MODEL),
        ),
    ]
